[build]
  command = "gem install bundler -v '< 2' && npm run build && mv _site _site_help && mkdir _site && mv _site_help _site/help"
  publish = "_site"

[context.production]
  command = "gem install bundler -v '< 2' && npm run build && jekyll algolia && mv _site _site_help && mkdir _site && mv _site_help _site/help"
  publish = "_site"

[[redirects]]
  from = "/"
  to = "/help"
  status = 302

[[redirects]]
  from = "/help"
  to = "/help/en"
  status = 302

[[redirects]]
  from = "/help/ja/education/"
  to = "/help/ja/education/クラスの作成.html"
  status = 302

[[redirects]]
  from = "/help/en/education/site-license.html"
  to = "/help/en/education/plan.html"
  status = 302